lawremi/CustomOreGen

gregtech/Gregtech.xml
gregtech/Materials.java
gregtech/materials
src/main/resources/config/modules/Gregtech.xml

The recent changes to harvest levels makes progression in GT5 a little too hard. For example:
Most Iron sources such as BandedIron, Magnesite need a level 4 pickaxe (Tungsten Steel, or one more than Diamond!). Similar situations for copper, tin. While some sand or small veins deposits are present in the world they are far too rare.
See http://ftb.gamepedia.com/Pickaxe_(GregTech)
First commit is the changed Gregtech (5) XML.
The second commit has a hacky python script under the "gregtech" dir which automatically generates a new Gregtech.xml with the same harvest levels as Gregtech, though sand veins are left at a very soft/easy source of some materials. This is not required change, is for reference/modification.
Suggestion for sand deposits of iron might be to replace or supplement …

Set harvest level to match GregTech 5 almost exactly.

---

src/main/resources/config/modules/AppliedEnergistics.xml
src/main/resources/config/modules/ArsMagicka2.xml
src/main/resources/config/modules/BiomesOPlenty.xml
src/main/resources/config/modules/Chisel2.xml
src/main/resources/config/modules/DenseOres.xml
src/main/resources/config/modules/ElectriCraft.xml
src/main/resources/config/modules/Forestry.xml
src/main/resources/config/modules/FossilsandArchaeology.xml
src/main/resources/config/modules/Metallurgy4.xml
src/main/resources/config/modules/MineChem.xml
src/main/resources/config/modules/MinecraftComesAlive.xml
src/main/resources/config/modules/NetherOres.xml
src/main/resources/config/modules/Netherrocks.xml
src/main/resources/config/modules/PamsHarvestCraft.xml
src/main/resources/config/modules/ProjectRed.xml
src/main/resources/config/modules/RailCraft.xml
src/main/resources/config/modules/ReactorCraft.xml
src/main/resources/config/modules/SimpleOres.xml
src/main/resources/config/modules/Thaumcraft4.xml
src/main/resources/config/modules/ThermalFoundation.xml
src/main/resources/config/modules/TinkersConstruct.xml
src/main/resources/config/modules/VanillaMinecraft.xml

Up until now, I had neglected to set huge veins to the huge veins preset, so I had been under the assumption that they were like the layered veins, only slightly larger and harder to find.  To make them easier to spot, I added hint veins.
Now that I've found the mistake, I fixed the preset, and discovered that the extremely long tendrils prevents the need for hint veins.  Besides, hint or not, Draco's "Ore Flowers" mod does a nice job of hinting at an ore's presence. ;)
I also added huge veins for vanilla iron, gold, and nether quartz.
Finally, I've also fixed some comments to give the name of the mod as "Custom Ore Generation," rather than "Custom Ore Gen," which is something of a itch that needed scratching. ;)

The Huge Vein Project.

---

src/main/resources/config/modules/DenseOres.xml

Made a typo in the INI file; Sprocket gave Nether Quartz the default material replacement of minecraft:stone.  The replace field is now correct.

Nether quartz was replacing stone instead of netherrack.  Fixed.

---

src/main/resources/config/modules/AppliedEnergistics.xml
src/main/resources/config/modules/ArsMagica2.xml
src/main/resources/config/modules/BiomesOPlenty.xml
src/main/resources/config/modules/Chisel2.xml
src/main/resources/config/modules/DenseOres.xml
src/main/resources/config/modules/ElectriCraft.xml
src/main/resources/config/modules/Factorization.xml
src/main/resources/config/modules/Forestry.xml
src/main/resources/config/modules/FossilsandArchaeology.xml
src/main/resources/config/modules/GeoStrata.xml
src/main/resources/config/modules/Metallurgy4.xml
src/main/resources/config/modules/MineChem.xml
src/main/resources/config/modules/MinecraftComesAlive.xml
src/main/resources/config/modules/NetherOres.xml
src/main/resources/config/modules/Netherrocks.xml
src/main/resources/config/modules/PamsHarvestCraft.xml
src/main/resources/config/modules/ProjectRed.xml
src/main/resources/config/modules/RailCraft.xml
src/main/resources/config/modules/ReactorCraft.xml
src/main/resources/config/modules/SimpleOres.xml
src/main/resources/config/modules/Thaumcraft4.xml
src/main/resources/config/modules/ThermalFoundation.xml
src/main/resources/config/modules/TinkersConstruct.xml
src/main/resources/config/modules/VanillaMinecraft.xml

This is another "I updated Sprocket" release.  Most of the changes are pretty cosmetic, but some important fixes were made, and more are on the way (including multi-block distributions, and an overhaul on the geode configuration).
* FIXED: Vanilla clay spawns in all biomes except desert, with a preference for rivers, ocean, beaches, and swamps.  Previously, despite configuration, clay would not spawn in non-watery biomes, due to negative-weight biometype assuming all other biomes were not to be used, either.
* FIXED: Railcraft Abyssal stone no longer needs a specific substitute distribution to remove it; the substitution was added to the initial stanza.
* FIXED: Previously, blocks with a meta value of 0 made it explicit (minecraft:stone:0).  The explicit ":0" has been removed from all …

Some fixes, some changes

---

src/main/resources/config/CustomOreGen_Config_Default.xml
src/main/resources/config/modules/AppliedEnergistics.xml
src/main/resources/config/modules/ArsMagica2.xml
src/main/resources/config/modules/BiomesOPlenty.xml
src/main/resources/config/modules/Chisel2.xml
src/main/resources/config/modules/DenseOres.xml
src/main/resources/config/modules/ElectriCraft.xml
src/main/resources/config/modules/Factorization.xml
src/main/resources/config/modules/Forestry.xml
src/main/resources/config/modules/FossilsandArchaeology.xml
src/main/resources/config/modules/GeoStrata.xml
src/main/resources/config/modules/Mekanism.xml
src/main/resources/config/modules/Metallurgy4.xml
src/main/resources/config/modules/MineChem.xml
src/main/resources/config/modules/MinecraftComesAlive.xml
src/main/resources/config/modules/PamsHarvestCraft.xml
src/main/resources/config/modules/ProjectRed.xml
src/main/resources/config/modules/RailCraft.xml
src/main/resources/config/modules/ReactorCraft.xml
src/main/resources/config/modules/SimpleOres.xml
src/main/resources/config/modules/Thaumcraft4.xml
src/main/resources/config/modules/ThermalFoundation.xml
src/main/resources/config/modules/TinkersConstruct.xml
src/main/resources/config/modules/VanillaMinecraft.xml

After researching intended ore amounts by reading the original mods' source code on github, The vein sizes, chunk chances, and y levels have been recorded, and converted into COG ore configuration values. The final tally was reduced by 1/12 to account for the vanilla overabundance due to ores being spread out.
End results:
* Ores are as rare in vein and cloud form as they were in vanilla form... at least when compared to each other (the comparative rarity of iron, redstone, and certus quartz, for example, are consistent between vanilla, vein, and cloud).
* Heights have all be restored to their mod-specified levels.
* Dense Ores and Applied Energistics makes use of "weighted and mixed ores," in which a single vein can contain more than one ore type.
* All configurations now include a …

A lot of changes

---

src/main/resources/config/modules/AppliedEnergistics.xml
src/main/resources/config/modules/ArsMagica2.xml
src/main/resources/config/modules/BiomesOPlenty.xml
src/main/resources/config/modules/Chisel2.xml
src/main/resources/config/modules/DenseOres.xml
src/main/resources/config/modules/ElectriCraft.xml
src/main/resources/config/modules/Factorization.xml
src/main/resources/config/modules/Forestry.xml
src/main/resources/config/modules/FossilsandArchaeology.xml
src/main/resources/config/modules/GeoStrata.xml
src/main/resources/config/modules/Mekanism.xml
src/main/resources/config/modules/Metallurgy4.xml
src/main/resources/config/modules/MineChem.xml
src/main/resources/config/modules/MinecraftComesAlive.xml
src/main/resources/config/modules/PamsHarvestCraft.xml
src/main/resources/config/modules/ProjectRed.xml
src/main/resources/config/modules/RailCraft.xml
src/main/resources/config/modules/ReactorCraft.xml
src/main/resources/config/modules/SimpleOres.xml
src/main/resources/config/modules/Thaumcraft4.xml
src/main/resources/config/modules/ThermalFoundation.xml
src/main/resources/config/modules/TinkersConstruct.xml
src/main/resources/config/modules/VanillaMinecraft.xml

The following changes:
* Geodes would break down if scaled too large; this is the result of the way the inner-ore and bubble deposits were scaling with the shell stone (they were scaling faster).  FIXED.
* Geodes had way too much ores.  Nerfed a little; now there's an average of 1-3 ores per geode (with a preference for Lapis)
* The random number seeds were apparently shared between all ores in some of the new distributions.  New static seed numbers were assigned.
* Originally, all spaces were stripped from options.  This resulted in problems with two-word biome names (like 'Deep Ocean').  The spaces stopped being stripped, but it was quickly discovered that those same strings now had an extra leding space (like ' Deep Ocean'), for the same result.  This time, the leading spaces were …

Fixed some mistakes, nerfed geode ores

---

src/main/resources/config/modules/AppliedEnergistics.xml
src/main/resources/config/modules/ArsMagica2.xml
src/main/resources/config/modules/BiomesOPlenty.xml
src/main/resources/config/modules/Chisel2.xml
src/main/resources/config/modules/DenseOres.xml
src/main/resources/config/modules/ElectriCraft.xml
src/main/resources/config/modules/Factorization.xml
src/main/resources/config/modules/Forestry.xml
src/main/resources/config/modules/FossilsandArchaeology.xml
src/main/resources/config/modules/GeoStrata.xml
src/main/resources/config/modules/Mekanism.xml
src/main/resources/config/modules/Metallurgy4.xml
src/main/resources/config/modules/MineChem.xml
src/main/resources/config/modules/MinecraftComesAlive.xml
src/main/resources/config/modules/NetherOres.xml
src/main/resources/config/modules/Netherrocks.xml
src/main/resources/config/modules/PamsHarvestCraft.xml
src/main/resources/config/modules/ProjectRed.xml
src/main/resources/config/modules/RailCraft.xml
src/main/resources/config/modules/ReactorCraft.xml
src/main/resources/config/modules/SimpleOres.xml
src/main/resources/config/modules/Thaumcraft4.xml
src/main/resources/config/modules/ThermalFoundation.xml
src/main/resources/config/modules/TinkersConstruct.xml
src/main/resources/config/modules/TinkersSteelworks.xml
src/main/resources/config/modules/VanillaMinecraft.xml

Thanks to some mathematical help from Keybounce, I've figured out how to make the distributions respect the square-cube law.  The Railcraft poor ores, in particular, are now actually under control for the first time.  The configurations generated by Sprocket are now closer to an accurate representation of the vanilla commonness.
Also overhauled configurations for Netherrocks and Tinker's Steelworks.

Square-Cube Compliance

---

src/main/resources/config/modules/Chisel2.xml
src/main/resources/config/modules/ElectriCraft.xml
src/main/resources/config/modules/Forestry.xml
src/main/resources/config/modules/GeoStrata.xml
src/main/resources/config/modules/Metallurgy4.xml
src/main/resources/config/modules/NetherOres.xml
src/main/resources/config/modules/Netherrocks.xml
src/main/resources/config/modules/PamsHarvestCraft.xml
src/main/resources/config/modules/ReactorCraft.xml
src/main/resources/config/modules/SimpleOres.xml
src/main/resources/config/modules/Thaumcraft4.xml
src/main/resources/config/modules/ThermalFoundation.xml
src/main/resources/config/modules/TinkersConstruct.xml

All ores whose average y level is above 64 were changed from using a normal distribution to a uniform distribution, in order to ensure enough is below sea level (and actually in the ground) to actually make the oregen worthwhile.
Also, Changed Cobalt and Ardite from Layered Veins to Small Deposits.

Uniform y>64 avg, TiC Ores fixed

---

src/main/resources/config/modules/VanillaMinecraft.xml

Made a mistake in the standardgen ores; frequencies and sizes had their values switched for most of the ores (except emerald, clay, and quartz).  Fixed.

Had standard sizes/freqs reversed.  Fixed.

---

src/main/resources/config/CustomOreGen_Config_Default.xml

GregTech uses oredict values in order to override the ores generated by other mods.  Because of this, its current place in the load order needs to be corrected.  At this point, the gregtech configurations have been moved to last place, so they can override all other mods' ore placement with their own special form.

Rearranged Gregtech to follow other configs.

---

src/main/resources/config/modules/AppliedEnergistics.xml
src/main/resources/config/modules/ArsMagica2.xml
src/main/resources/config/modules/BiomesOPlenty.xml
src/main/resources/config/modules/Chisel2.xml
src/main/resources/config/modules/DenseOres.xml
src/main/resources/config/modules/ElectriCraft.xml
src/main/resources/config/modules/Factorization.xml
src/main/resources/config/modules/FlaxbeardsSteamcraft.xml
src/main/resources/config/modules/Forestry.xml
src/main/resources/config/modules/FossilsandArchaeology.xml
src/main/resources/config/modules/Galacticraft.xml
src/main/resources/config/modules/GeoStrata.xml
src/main/resources/config/modules/ImmersiveEngineering.xml
src/main/resources/config/modules/Mekanism.xml
src/main/resources/config/modules/Metallurgy4.xml
src/main/resources/config/modules/MineChem.xml
src/main/resources/config/modules/MinecraftComesAlive.xml
src/main/resources/config/modules/PamsHarvestCraft.xml
src/main/resources/config/modules/ProjectRed.xml
src/main/resources/config/modules/RailCraft.xml
src/main/resources/config/modules/ReactorCraft.xml
src/main/resources/config/modules/SimpleOres.xml
src/main/resources/config/modules/Thaumcraft4.xml
src/main/resources/config/modules/ThermalFoundation.xml
src/main/resources/config/modules/TinkersConstruct.xml
src/main/resources/config/modules/TinkersSteelworks.xml
src/main/resources/config/modules/VanillaMinecraft.xml

In order to resolve issues with stone mods like Underground Biomes, all generated oregens now make use of the "stone," "dirt," "gravel," and "sand" ore dictionary entries.  In this way, the ore will spawn, regardless of the type of stone, sand, gravel, or dirt is being used in a world.  Thankfully, grass and mycelium are not oredicted to dirt, so hint veins and clay won't become painfully obvious.

Stone, sand, dirt, and gravel now use oredict.

---

src/main/resources/config/modules/AppliedEnergistics.xml
src/main/resources/config/modules/ArsMagica2.xml
src/main/resources/config/modules/BiomesOPlenty.xml
src/main/resources/config/modules/Chisel2.xml
src/main/resources/config/modules/DenseOres.xml
src/main/resources/config/modules/ElectriCraft.xml
src/main/resources/config/modules/Factorization.xml
src/main/resources/config/modules/FlaxbeardsSteamcraft.xml
src/main/resources/config/modules/Forestry.xml
src/main/resources/config/modules/FossilsandArchaeology.xml
src/main/resources/config/modules/Galacticraft.xml
src/main/resources/config/modules/GeoStrata.xml
src/main/resources/config/modules/ImmersiveEngineering.xml
src/main/resources/config/modules/Mekanism.xml
src/main/resources/config/modules/Metallurgy4.xml
src/main/resources/config/modules/MineChem.xml
src/main/resources/config/modules/MinecraftComesAlive.xml
src/main/resources/config/modules/NetherOres.xml
src/main/resources/config/modules/Netherrocks.xml
src/main/resources/config/modules/PamsHarvestCraft.xml
src/main/resources/config/modules/ProjectRed.xml
src/main/resources/config/modules/RailCraft.xml
src/main/resources/config/modules/ReactorCraft.xml
src/main/resources/config/modules/SimpleOres.xml
src/main/resources/config/modules/Thaumcraft4.xml
src/main/resources/config/modules/ThermalFoundation.xml
src/main/resources/config/modules/TinkersConstruct.xml
src/main/resources/config/modules/TinkersSteelworks.xml
src/main/resources/config/modules/VanillaMinecraft.xml

As requested, Sprocket has been updated to remove the block check from <Replaces> and <ReplacesOre> commands.

Removed block check from replacement commands.

---

src/main/resources/config/CustomOreGen_Config_Default.xml

The order is now as follows:
* Stone is first; now that all oregens now replace the 'stone' oredict, let's push the stone to the front of the queue.
* Next in line is extra caves; might as well reduce the number of replacements before they're made; this might improve performance a little bit.
* Next, vanilla takes priority.
* Next, dense ores is in place to replace vanilla ores with a 10:1 vanilla/dense mix.
* Next, the bulk of the oregen configurations are added, in alphabetical order; these do not interact with one another, so order doesn't matter.
* Finally, Gregtech replaces a lot of the above oregens with its own designs, so it should be last.

Rearrenged configs in the default.

---

src/main/resources/config/modules/AppliedEnergistics.xml
src/main/resources/config/modules/ArsMagica2.xml
src/main/resources/config/modules/BiomesOPlenty.xml
src/main/resources/config/modules/DenseOres.xml
src/main/resources/config/modules/ElectriCraft.xml
src/main/resources/config/modules/Factorization.xml
src/main/resources/config/modules/FlaxbeardsSteamcraft.xml
src/main/resources/config/modules/Forestry.xml
src/main/resources/config/modules/FossilsandArchaeology.xml
src/main/resources/config/modules/Galacticraft.xml
src/main/resources/config/modules/GeoStrata.xml
src/main/resources/config/modules/ImmersiveEngineering.xml
src/main/resources/config/modules/Mekanism.xml
src/main/resources/config/modules/Metallurgy4.xml
src/main/resources/config/modules/MineChem.xml
src/main/resources/config/modules/MinecraftComesAlive.xml
src/main/resources/config/modules/NetherOres.xml
src/main/resources/config/modules/Netherrocks.xml
src/main/resources/config/modules/PamsHarvestCraft.xml
src/main/resources/config/modules/ProjectRed.xml
src/main/resources/config/modules/RailCraft.xml
src/main/resources/config/modules/ReactorCraft.xml
src/main/resources/config/modules/SimpleOres.xml
src/main/resources/config/modules/Thaumcraft4.xml
src/main/resources/config/modules/ThermalFoundation.xml
src/main/resources/config/modules/TinkersConstruct.xml
src/main/resources/config/modules/TinkersSteelworks.xml
src/main/resources/config/modules/VanillaMinecraft.xml

All standard distributions have been halved; this is because the values should be averages, rather than maximums; the deviations go in both directions.  Additionally, all standard distributions have deviations that match their averages; this means they can be anything from 0 to the original maximum values.
Other fixes:
* Some tweaks to other distributions had apparently been overlooked in placement until now.  Fixed.
* Biomes O'Plenty's oregen was missing height values.  Fixed.
* Chisel 2's oregens were missing height values.  Fixed.
* Geostrata's Standard Frequency values were missing.  Fixed.
* Metallurgy 4's height values were missing.  Fixed.
* Nether Ores' height values are missing.  Fixed.
* Netherrocks' height values are missing.  Fixed.

Fixed vanilla oregen values

---

src/main/resources/config/modules/AppliedEnergistics.xml
src/main/resources/config/modules/ArsMagica2.xml
src/main/resources/config/modules/BiomesOPlenty.xml
src/main/resources/config/modules/Chisel2.xml
src/main/resources/config/modules/DenseOres.xml
src/main/resources/config/modules/ElectriCraft.xml
src/main/resources/config/modules/Factorization.xml
src/main/resources/config/modules/FlaxbeardsSteamcraft.xml
src/main/resources/config/modules/Forestry.xml
src/main/resources/config/modules/FossilsandArchaeology.xml
src/main/resources/config/modules/Galacticraft.xml
src/main/resources/config/modules/GeoStrata.xml
src/main/resources/config/modules/ImmersiveEngineering.xml
src/main/resources/config/modules/Mekanism.xml
src/main/resources/config/modules/Metallurgy4.xml
src/main/resources/config/modules/MineChem.xml
src/main/resources/config/modules/MinecraftComesAlive.xml
src/main/resources/config/modules/NetherOres.xml
src/main/resources/config/modules/Netherrocks.xml
src/main/resources/config/modules/PamsHarvestCraft.xml
src/main/resources/config/modules/ProjectRed.xml
src/main/resources/config/modules/RailCraft.xml
src/main/resources/config/modules/ReactorCraft.xml
src/main/resources/config/modules/SimpleOres.xml
src/main/resources/config/modules/Thaumcraft4.xml
src/main/resources/config/modules/ThermalFoundation.xml
src/main/resources/config/modules/TinkersConstruct.xml
src/main/resources/config/modules/TinkersSteelworks.xml
src/main/resources/config/modules/VanillaMinecraft.xml

The following are now complete.
* All stone "ores" now use the Stratum Clouds distribution by default.
* All configuration sections check for block existence before showing any options other than "None."
* The block checks still remain in the "OreBlock" entries, in order to ensure one missing block doesn't cause an error.

The Big One

---

src/main/resources/config/modules/AppliedEnergistics.xml
src/main/resources/config/modules/ArsMagica2.xml
src/main/resources/config/modules/BiomesOPlenty.xml
src/main/resources/config/modules/Chisel2.xml
src/main/resources/config/modules/DenseOres.xml
src/main/resources/config/modules/ElectriCraft.xml
src/main/resources/config/modules/Factorization.xml
src/main/resources/config/modules/FlaxbeardsSteamcraft.xml
src/main/resources/config/modules/Forestry.xml
src/main/resources/config/modules/FossilsandArchaeology.xml
src/main/resources/config/modules/Galacticraft.xml
src/main/resources/config/modules/GeoStrata.xml
src/main/resources/config/modules/ImmersiveEngineering.xml
src/main/resources/config/modules/Mekanism.xml
src/main/resources/config/modules/Metallurgy4.xml
src/main/resources/config/modules/MineChem.xml
src/main/resources/config/modules/MinecraftComesAlive.xml
src/main/resources/config/modules/NetherOres.xml
src/main/resources/config/modules/Netherrocks.xml
src/main/resources/config/modules/PamsHarvestCraft.xml
src/main/resources/config/modules/ProjectRed.xml
src/main/resources/config/modules/RailCraft.xml
src/main/resources/config/modules/ReactorCraft.xml
src/main/resources/config/modules/SimpleOres.xml
src/main/resources/config/modules/Thaumcraft4.xml
src/main/resources/config/modules/ThermalFoundation.xml
src/main/resources/config/modules/TinkersConstruct.xml
src/main/resources/config/modules/TinkersSteelworks.xml
src/main/resources/config/modules/VanillaMinecraft.xml

* All ore and block (re)placement commands have had their block checks removed. 
* All distributions now check for block existence before adding distribution options other than "None"
* All block checks for distributions now use AND instead of OR; if one single block is missing, the distribution won't show anything but NONE.
NOTE: Railcraft's blocks continue to exist, even if they've been disabled in the config.  It's the weirdest thing, but that's something that will need to be handled on Railcraft's side.

Overhauled block existence checks.

---

src/main/resources/config/modules/AppliedEnergistics.xml
src/main/resources/config/modules/ArsMagica2.xml
src/main/resources/config/modules/BiomesOPlenty.xml
src/main/resources/config/modules/DenseOres.xml
src/main/resources/config/modules/ElectriCraft.xml
src/main/resources/config/modules/Factorization.xml
src/main/resources/config/modules/FlaxbeardsSteamcraft.xml
src/main/resources/config/modules/Forestry.xml
src/main/resources/config/modules/FossilsandArchaeology.xml
src/main/resources/config/modules/Galacticraft.xml
src/main/resources/config/modules/ImmersiveEngineering.xml
src/main/resources/config/modules/IndustrialCraft2.xml
src/main/resources/config/modules/MagnetiCraft.xml
src/main/resources/config/modules/Mariculture.xml
src/main/resources/config/modules/Mekanism.xml
src/main/resources/config/modules/Metallurgy4.xml
src/main/resources/config/modules/MineChem.xml
src/main/resources/config/modules/MinecraftComesAlive.xml
src/main/resources/config/modules/NetherOres.xml
src/main/resources/config/modules/Netherrocks.xml
src/main/resources/config/modules/Nuclearcraft.xml
src/main/resources/config/modules/PamsHarvestCraft.xml
src/main/resources/config/modules/ProjectRed.xml
src/main/resources/config/modules/RailCraft.xml
src/main/resources/config/modules/ReactorCraft.xml
src/main/resources/config/modules/SimpleOres.xml
src/main/resources/config/modules/Thaumcraft4.xml
src/main/resources/config/modules/ThermalFoundation.xml
src/main/resources/config/modules/TinkersConstruct.xml
src/main/resources/config/modules/VanillaMinecraft.xml

Now, dirt and gravel are no longer using the oredicts; they are using the standard block names again.

Removed dirt and gravel oredicts from hint veins.

---

src/main/resources/config/modules/MinecraftSpecialRules.xml

Supplemental caves now can never pass Y=60 in height; this should preserve villages, and keep the caverns underground.

Clamped supplemental caves to <y=60.

---

src/main/resources/config/modules/BiomesOPlenty.xml
src/main/resources/config/modules/DenseOres.xml
src/main/resources/config/modules/MagnetiCraft.xml
src/main/resources/config/modules/Mariculture.xml
src/main/resources/config/modules/Nuclearcraft.xml
src/main/resources/config/modules/ProjectRed.xml
src/main/resources/config/modules/RailCraft.xml
src/main/resources/config/modules/ReactorCraft.xml
src/main/resources/config/modules/Thaumcraft4.xml
src/main/resources/config/modules/TinkersConstruct.xml
src/main/resources/config/modules/VanillaMinecraft.xml

* Ores with an average spawn height of >64 now use uniform distribution to prevent the bulk of ores from spawning in midair (which means that they won't spawn).
* ReactorCraft Fluorite ore has been heavily nerfed; each distribution is now 1/8 the size and frequency.  Now the ore is more in-line with the original spawn distribution, while keeping the veins single-color.
* Added Cloud distributions to Thaumcraft infused stone.
* Tweaked some other oregens.

Some oregen fixes

---

src/main/java/CustomOreGen/CustomOreGenBase.java
src/main/resources/config/CustomOreGen_Config_Default.xml
src/main/resources/config/modules/Mimicry.xml
src/main/resources/config/modules/VanillaMinecraft.xml

The Mimicry mod was added to the configurations list.  Additionally, scaling for vanilla clay was changed from base to sea level (to ensure scaling remains locked at 64).

New mod configuration

---

src/main/java/CustomOreGen/CustomOreGenBase.java
src/main/resources/config/CustomOreGen_Config_Default.xml
src/main/resources/config/modules/Vanilla.xml

All instances of "Vanilla Minecraft" or "VanillaMinecraft" have been replaced with "Vanilla".

Renamed "Vanilla Minecraft" to just "Vanilla"

---

src/main/resources/config/modules/Metallurgy4.xml
src/main/resources/config/modules/Mimicry.xml
src/main/resources/config/modules/Netherrocks.xml

* AshStone name has been corrected in the generator.
* The surface of the End's island is at y=64; any ore generation above that level is wasted.  So, all end ores now generate to a maximum of y=64.

Minor Fixes

---

src/main/java/CustomOreGen/Config/ValidatorDistribution.java
src/main/java/CustomOreGen/Config/ValidatorTouchingDescriptor.java
src/main/java/CustomOreGen/Server/IOreDistribution.java
src/main/java/CustomOreGen/Server/MapGenOreDistribution.java
src/main/java/CustomOreGen/Server/WorldGenSubstitution.java
src/main/java/CustomOreGen/Util/BlockArrangement.java
src/main/java/CustomOreGen/Util/TouchingDescriptor.java
src/main/java/CustomOreGen/Util/TouchingDescriptorList.java

Adds additional functionality to `PlacesBeside` configuration option for ore distributions.  A new XML element has been added called `Touches` that has a superset of the `PlacesBeside` functionality.  `PlacesBeside` will still be kept for legacy usage and existing configuration files will not be affected for users.
The new configuration option has the following features:
- Must be placed within an ore distribution (Veins, Cloud, StandardGen etc.).
- `block` attribute sets the block type to check for
- `block` can be a regular expression like the PlacesBeside command.  This is controlled by appending 'Regexp' to the touches command (`TouchesRegexp` instead of `Touches`).  Alternatively you can also append 'Ore'.
- `minimumTouches` and `maximumTouches` define the number of touching blocks …

Add 'Touches' placement restriction for configuration
